### PR TITLE
Updated to Godot4

### PR DESCRIPTION
**Pull request by shinspiegel**
Hi,

I updated this addon to Godot 4, I tested on my local development (macOS M1), 
I will test on my linux machine but I can test on the windows, 

Hope this can be helpful

### CODE REVIEW

**Comment by shinspiegel** [comment]
I added the types, and also fixed some small snags that I did find.
I tested and looks ok on the mac machine.

**Comment by jotson** [comment]
Thanks! Do you happen to know how to ship multiple versions of a plugin to the Godot asset lib? I'd want to have the 4.0 and the 3.5 version both available until at least after 4.0 hits stable.

**Comment by paddy-exe** [comment]
@jotson I think in this case you can create a separate entrance by manually uploading it once and creating a new entrance with 4.0 as a specified version and then use the ID in the upload CI/CD instead of the 3.x one🤔

Edit: @shinspiegel Yes, would be my idea as well

**Comment by shinspiegel** [comment]
I've no idea...
Maybe a secondary branch to hold the 4.0 version while isn't stable.
And create a new entry in the asset library... Right?

**Comment by jotson** [comment]
@shinspiegel Hey shin! Just merged this into new branch godot4

Please give it a whirl and make sure it still works for you on your mac. I'll be testing it here on my linux workstation. If it looks good I'll setup a new asset library entry for it.

**Comment by paddy-exe** [comment]
So I tested it on Win10 and noticed several things:
## This here gets out of bounds if minimized too much
image

## The font of Gravity8 doesn't get applied to the spawned character effects:
image

**Comment by shinspiegel** [comment]
OH MY GOD! 
There is much more to fix it. 
I'll take another look and double-check for some rough-edges...

Thanks for the images @paddy-exe  :D

Also, for some reason, the project does not want to be open on beta 6...
Back to the whiteboard... I'll try to figure out what happened.

**Pull request merged**
